//////////////////////////////////////////////////////////////////////
// Tim Rudowski
// Christopher Bubeck
// Senior Project
// Due Date:  11/29/00
//
// NOTE:  This entire file is Visual Studio machine generated...
//
// This file declares the CommandButton class.  The CommandButton class
// is used for the buttons on the main menu, such as PLAY, CHOOSE TRACK, etc.
// This file and commandbutton.cpp declare/define functions for the class.
// This is an ActiveX control, so the main code of the class has already
// been defined in FM20.dll.  This just provides a 'wrapper' so that the
// button's functions can be accessed.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_COMMANDBUTTON_H__8A0066D5_94EC_44B4_8E4D_A3F46D227CDB__INCLUDED_)
#define AFX_COMMANDBUTTON_H__8A0066D5_94EC_44B4_8E4D_A3F46D227CDB__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CCommandButton wrapper class

class CCommandButton : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCommandButton)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd7053240, 0xce69, 0x11cd, { 0xa7, 0x77, 0x0, 0xdd, 0x1, 0x14, 0x3c, 0x57 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetAutoSize(BOOL bNewValue);
	BOOL GetAutoSize();
	void SetBackColor(long nNewValue);
	long GetBackColor();
	void SetBackStyle(long nNewValue);
	long GetBackStyle();
	void SetCaption(LPCTSTR lpszNewValue);
	CString GetCaption();
	void SetEnabled(BOOL bNewValue);
	BOOL GetEnabled();
	void SetRefFont(LPDISPATCH newValue);
	COleFont GetFont();
	void SetForeColor(long nNewValue);
	long GetForeColor();
	void SetTakeFocusOnClick(BOOL bNewValue);
	BOOL GetTakeFocusOnClick();
	void SetLocked(BOOL bNewValue);
	BOOL GetLocked();
	void SetMouseIcon(LPDISPATCH newValue);
	void SetRefMouseIcon(LPDISPATCH newValue);
	CPicture GetMouseIcon();
	void SetMousePointer(long nNewValue);
	long GetMousePointer();
	void SetPicture(LPDISPATCH newValue);
	void SetRefPicture(LPDISPATCH newValue);
	CPicture GetPicture();
	void SetPicturePosition(long nNewValue);
	long GetPicturePosition();
	void SetAccelerator(LPCTSTR lpszNewValue);
	CString GetAccelerator();
	void SetWordWrap(BOOL bNewValue);
	BOOL GetWordWrap();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_COMMANDBUTTON_H__8A0066D5_94EC_44B4_8E4D_A3F46D227CDB__INCLUDED_)
