// playcontrol1.cpp
// This file provides a way for us to access the Visual Basic DirectPlay control.

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "playcontrol1.h"

/////////////////////////////////////////////////////////////////////////////
// CPlayControl

IMPLEMENT_DYNCREATE(CPlayControl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CPlayControl properties

/////////////////////////////////////////////////////////////////////////////
// CPlayControl operations

BOOL CPlayControl::Initialize_Connection(short* WhichConnection)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PI2;
	InvokeHelper(0x60030002, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		WhichConnection);
	return result;
}

BOOL CPlayControl::Create_Session(short* MaxPlayers, BSTR* SessionName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PI2 VTS_PBSTR;
	InvokeHelper(0x60030003, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		MaxPlayers, SessionName);
	return result;
}

BOOL CPlayControl::Join_Session()
{
	BOOL result;
	InvokeHelper(0x60030004, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

long CPlayControl::Create_Player(BSTR* PlayerName)
{
	long result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x60030005, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		PlayerName);
	return result;
}

BOOL CPlayControl::Destroy_Player(long* PlayerID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PI4;
	InvokeHelper(0x60030006, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		PlayerID);
	return result;
}

short CPlayControl::Get_Num_Players_Connected()
{
	short result;
	InvokeHelper(0x60030007, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

long CPlayControl::Get_PlayerID(short* WhichPlayer)
{
	long result;
	static BYTE parms[] =
		VTS_PI2;
	InvokeHelper(0x60030008, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		WhichPlayer);
	return result;
}

CString CPlayControl::Get_Player_Name(short* WhichPlayer)
{
	CString result;
	static BYTE parms[] =
		VTS_PI2;
	InvokeHelper(0x60030009, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		WhichPlayer);
	return result;
}

long CPlayControl::Get_Message_Count()
{
	long result;
	InvokeHelper(0x6003000a, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CPlayControl::Send_Position_Message_To_All(short* Car, short* Direct, double* XPos, double* YPos, double* Accel)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PI2 VTS_PI2 VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x6003000b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Car, Direct, XPos, YPos, Accel);
	return result;
}

BOOL CPlayControl::Send_Chat_Message_To_All(BSTR* Message)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x6003000c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Message);
	return result;
}

BOOL CPlayControl::Send_Start_Message_To_All(short* TotalPlay, short* Board, short* Mode, short* ExtraData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PI2 VTS_PI2 VTS_PI2 VTS_PI2;
	InvokeHelper(0x6003000d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		TotalPlay, Board, Mode, ExtraData);
	return result;
}

BOOL CPlayControl::Send_Bump_Message_To_All(short* Car, short* Dam, BOOL* goFor)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PI2 VTS_PI2 VTS_PBOOL;
	InvokeHelper(0x6003000e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Car, Dam, goFor);
	return result;
}

BOOL CPlayControl::Send_Winner_Message_To_All(short* Car, BSTR* Name)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PI2 VTS_PBSTR;
	InvokeHelper(0x6003000f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Car, Name);
	return result;
}

BOOL CPlayControl::Send_Draw_Message_To_All(short* WhichPowerUp, short* XPos, short* YPos)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PI2 VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030010, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		WhichPowerUp, XPos, YPos);
	return result;
}

BOOL CPlayControl::Send_Undraw_Message_To_All(short* WhichPowerUp, short* XPos, short* YPos)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PI2 VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030011, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		WhichPowerUp, XPos, YPos);
	return result;
}

BOOL CPlayControl::Send_Acquire_Message_To_All(short* Car)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PI2;
	InvokeHelper(0x60030012, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Car);
	return result;
}

BOOL CPlayControl::Send_UnAcquire_Message_To_All()
{
	BOOL result;
	InvokeHelper(0x60030013, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CString CPlayControl::Get_Chat_Message()
{
	CString result;
	InvokeHelper(0x60030014, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CPlayControl::Get_Position_Message(short* Car, short* Direct, double* XPos, double* YPos, double* Accel)
{
	static BYTE parms[] =
		VTS_PI2 VTS_PI2 VTS_PR8 VTS_PR8 VTS_PR8;
	InvokeHelper(0x60030016, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Car, Direct, XPos, YPos, Accel);
}

void CPlayControl::Get_Start_Message(short* TotalPlay, short* Board, short* Mode, short* ExtraData)
{
	static BYTE parms[] =
		VTS_PI2 VTS_PI2 VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030017, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 TotalPlay, Board, Mode, ExtraData);
}

void CPlayControl::Get_Bumped_Message(short* Car, short* Dam, BOOL* goFor)
{
	static BYTE parms[] =
		VTS_PI2 VTS_PI2 VTS_PBOOL;
	InvokeHelper(0x60030018, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Car, Dam, goFor);
}

void CPlayControl::Get_Winner_Message(short* Car, BSTR* Name)
{
	static BYTE parms[] =
		VTS_PI2 VTS_PBSTR;
	InvokeHelper(0x60030019, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Car, Name);
}

void CPlayControl::Get_PowerUp_Message(short* WhichPowerUp, short* XPos, short* YPos)
{
	static BYTE parms[] =
		VTS_PI2 VTS_PI2 VTS_PI2;
	InvokeHelper(0x6003001a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 WhichPowerUp, XPos, YPos);
}

void CPlayControl::Get_Acquire_Message(short* Car)
{
	static BYTE parms[] =
		VTS_PI2;
	InvokeHelper(0x6003001b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Car);
}

short CPlayControl::GetDPMessage()
{
	short result;
	InvokeHelper(0x6003001c, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}
