#if !defined(AFX_PLAYCONTROL1_H__5B0F9B4F_5F2A_4398_A8AB_98344E192000__INCLUDED_)
#define AFX_PLAYCONTROL1_H__5B0F9B4F_5F2A_4398_A8AB_98344E192000__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPlayControl wrapper class

class CPlayControl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPlayControl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x6efac6f0, 0x4252, 0x43c8, { 0x8e, 0xac, 0x61, 0xf4, 0x91, 0x98, 0xd4, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL Initialize_Connection(short* WhichConnection);
	// Initializes a connection.  WhichConnection should be a value
	// from 1 to 4 (see define section in Multiplayer.cpp)
	// Returns TRUE if successful, FALSE otherwise.

	BOOL Create_Session(short* MaxPlayers, BSTR* SessionName);
	// Creates a new session.  MaxPlayers is the maximum amount of players
	// that this session can handle.  SessionName is the name of the
	// session.
	// Returns TRUE if successful, FALSE otherwise.

	BOOL Join_Session();
	// Joins an already existing session on another machine.
	// Returns TRUE if successful, FALSE otherwise.

	long Create_Player(BSTR* PlayerName);
	// Creates a player with PlayerName being a string with the 
	// player's name
	// It returns a long which is the player's unique ID to DirectPlay
	// (returns 0 if creating a player was unsuccessful)

	BOOL Destroy_Player(long* PlayerID);
	// Destroys a player with unique ID PlayerID
	// Returns TRUE if successful, FALSE otherwise.

	short Get_Num_Players_Connected();
	// Returns the number of players connected in the current session.

	long Get_PlayerID(short* WhichPlayer);
	// Gets a unique ID for a player WhichPlayer 
	// WhichPlayer should be between 1 and the number of players
	// connected in the current session.

	CString Get_Player_Name(short* WhichPlayer);
	// Retrieve a player's name

	long Get_Message_Count();
	// How many messages do we have waiting for us in our queue?

	BOOL Send_Position_Message_To_All(short* Car, short* Direct, double* XPos, double* YPos, double* Accel);
	// Sends a position message to all players in the session.
	// The number of the car, its direction, position, and speed are
	// passed.

	// The following functions send messages to all players
	// The type of information that must be passed is different for
	// each type of message.
	// Each function returns TRUE if successful, FALSE otherwise.

	BOOL Send_Chat_Message_To_All(BSTR* Message);
	BOOL Send_Start_Message_To_All(short* TotalPlay, short* Board, short* Mode, short* ExtraData);
	BOOL Send_Bump_Message_To_All(short* Car, short* Dam, BOOL* goFor);
	BOOL Send_Winner_Message_To_All(short* Car, BSTR* Name);
	BOOL Send_Draw_Message_To_All(short* WhichPowerUp, short* XPos, short* YPos);
	BOOL Send_Undraw_Message_To_All(short* WhichPowerUp, short* XPos, short* YPos);
	BOOL Send_Acquire_Message_To_All(short* Car);
	BOOL Send_UnAcquire_Message_To_All();

	// short Get_Total_Players();
	// Not implemented

	// The following functions retrieve data stored in the DirectPlay
	// control.  The type of information returned depends on the message.

	CString Get_Chat_Message();
	void Get_Position_Message(short* Car, short* Direct, double* XPos, double* YPos, double* Accel);
	void Get_Start_Message(short* TotalPlay, short* Board, short* Mode, short* ExtraData);
	void Get_Bumped_Message(short* Car, short* Dam, BOOL* goFor);
	void Get_Winner_Message(short* Car, BSTR* Name);
	void Get_PowerUp_Message(short* WhichPowerUp, short* XPos, short* YPos);
	void Get_Acquire_Message(short* Car);

	// BOOL Initialize_With_Port(long* Port, BSTR* IP);
	// Not implemented

	short GetDPMessage();
	// Returns the type of message we have received.
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PLAYCONTROL1_H__5B0F9B4F_5F2A_4398_A8AB_98344E192000__INCLUDED_)
